import { getDb, now } from '../database/db';
export async function listBatches() { const d = await getDb(); return d.getAllAsync<any>('SELECT * FROM batches ORDER BY name'); }
export async function addBatch(name: string, year: string) { const d = await getDb(); await d.runAsync('INSERT INTO batches(name,academic_year,created_at) VALUES(?,?,?)', name, year, now()); }
export async function listStudents(batchId?: number) { const d = await getDb(); return batchId ? d.getAllAsync<any>('SELECT s.*,b.name batch_name FROM students s JOIN batches b ON b.id=s.batch_id WHERE s.batch_id=? AND s.active=1 ORDER BY s.name', batchId) : d.getAllAsync<any>('SELECT s.*,b.name batch_name FROM students s JOIN batches b ON b.id=s.batch_id WHERE s.active=1 ORDER BY s.name'); }
export async function addStudent(s: any) { const d = await getDb(); const t = now(); await d.runAsync('INSERT INTO students(code,name,photo_uri,address,student_mobile,guardian_name,guardian_relationship,guardian_mobile,batch_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)', s.code, s.name, s.photoUri || null, s.address || null, s.studentMobile || null, s.guardianName, s.guardianRelationship || null, s.guardianMobile || null, s.batchId, t, t); }
export async function todayAttendance() { const d = await getDb(); return d.getAllAsync<any>(`SELECT a.*,s.name student_name,b.name batch_name FROM attendance a JOIN students s ON s.id=a.student_id JOIN batches b ON b.id=s.batch_id WHERE a.attendance_date=date('now','localtime') ORDER BY a.in_time DESC`); }
export async function recordIn(studentId: number, confidence: number) { const d = await getDb(); const t = now(); const r = await d.runAsync(`INSERT INTO attendance(student_id,attendance_date,in_time,status,confidence,created_at) VALUES(?,date('now','localtime'),?,'PRESENT',?,?) ON CONFLICT(student_id,attendance_date) DO UPDATE SET in_time=COALESCE(attendance.in_time,excluded.in_time),confidence=excluded.confidence,status='PRESENT'`, studentId, t, confidence, t); return r; }
export async function recordOut(studentId: number) { const d = await getDb(); await d.runAsync(`UPDATE attendance SET out_time=? WHERE student_id=? AND attendance_date=date('now','localtime')`, now(), studentId); }
export async function findStudentBySlot(slot: number) { const d = await getDb(); return d.getFirstAsync<any>('SELECT s.*,f.finger_name,f.device_slot FROM fingerprints f JOIN students s ON s.id=f.student_id WHERE f.device_slot=? AND s.active=1', slot); }
export async function saveFingerprint(studentId: number, fingerName: string, slot: number, template: string) { const d = await getDb(); const t = now(); await d.runAsync('INSERT INTO fingerprints(student_id,finger_name,device_slot,template,created_at,updated_at) VALUES(?,?,?,?,?,?)', studentId, fingerName, slot, template, t, t); }
export async function stats() { const d = await getDb(); const students = await d.getFirstAsync<any>('SELECT COUNT(*) c FROM students WHERE active=1'); const batches = await d.getFirstAsync<any>('SELECT COUNT(*) c FROM batches WHERE active=1'); const present = await d.getFirstAsync<any>(`SELECT COUNT(*) c FROM attendance WHERE attendance_date=date('now','localtime') AND in_time IS NOT NULL`); return { students: students?.c || 0, batches: batches?.c || 0, present: present?.c || 0 }; }
